version: "2"
services:
  web:
    build: .
    ports:
      - "8081:8081"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
